### ISSUE TITLE
i18next integration fails to work with remix-i18next v6.x

### ISSUE THREAD

**Issue by usr3** [sergiodxa/remix-hono#163]
Hi,
Since the update to remix-i18next (#158), the RemixI18Next server instance fails to work with remix-hono.

The instance remains undefined as thrown in this error:
`X [ERROR] TypeError: Cannot read properties of undefined (reading 'order')`
`at LanguageDetector2.isSessionOnly`

**Comment by sergiodxa** [comment]
Should be fixed in [v0.0.16](https://github.com/sergiodxa/remix-hono/releases/tag/v0.0.16)
