### ISSUE TITLE
MiddlewareHandler type incompatibility with Hono 4.6.x

### ISSUE THREAD

**Issue by pandapaul** [sergiodxa/remix-hono#295]
When using Hono 4.6.x, there appears to be a minor type incompatibility:
```
Argument of type 'MiddlewareHandler<any, any, {}>' is not assignable to parameter of type 'MiddlewareHandler<BlankEnv, "*", {}>'
```

Perhaps resolvable by https://github.com/sergiodxa/remix-hono/pull/290 or similar.

**Comment by itorz7** [comment]
dump +

**Comment by sergiodxa** [comment]
Latest release uses the latest version of Hono and has no type errors so it should work now.
