### ISSUE TITLE
0.0.17 codes.forEach is not a function

### ISSUE THREAD

**Issue by JasonColeyNZ** [sergiodxa/remix-hono#300]
just upgraded from 0.0.16 to 0.0.17 and statred receiving the error....

TypeError: codes.forEach is not a function

 at LanguageUtil.getBestMatchFromCodes (file:///Users/imac27/Repos/ems-fly-rr7/node_modules/i18next/dist/esm/i18next.js:923:11)

I tried to upgrade i18next and the error is still there.

Looking further into it now..

**Comment by JasonColeyNZ** [comment]
I get the following when I put a console in the i18next.js ChangeLanguage function..
<img width="854" alt="Screenshot 2024-12-13 at 11 22 49 am" src="https://github.com/user-attachments/assets/bae4a4f7-2d7e-4e8d-9f70-0d1a03b41338" />

Like I said I have no issues rolling back to 0.0.16? very weird. Its like the translation function is being sent in as a string, and changeLanguage is treating it as a string, until it pases the value to the setLng, which checks for a string, then if not defaults to thinking its an array.

**Comment by JasonColeyNZ** [comment]
OK const locale = i18next.getLocale(c) is returning the function string, and I am using this in the entry.server.tsx

	const lng = appContext.lang
	**console.log("lng", lng) //this is the function string [Function: fixedT] { lng: 'en', ns: undefined, keyPrefix: undefined }**
	// biome-ignore lint/suspicious/noExplicitAny: <explanation>
	const ns = i18nextOpts.getRouteNamespaces(context as any)

	await instance
		.use(initReactI18next) // Tell our instance to use react-i18next
		.init({
			...i18n, // spread the configuration
			lng, // The locale we detected above
			ns, // The namespaces the routes about to render wants to use

			resources,
		})

**Comment by JasonColeyNZ** [comment]
And I just rolled back to confirm, with changing nothing, and it works correctly with 0.0.16

**Comment by JasonColeyNZ** [comment]
In the i18next.js of remix-hono the createMiddleware function is returning the correct value...

export function i18next(options) {
    return createMiddleware(async (c, next) => {
        let i18n = options instanceof RemixI18Next ? options : new RemixI18Next(options);
        let locale = await i18n.getLocale(c.req.raw);
        console.log('i18n.getLocale(c.req.raw)', await i18n.getLocale(c.req.raw))
				let t = await i18n.getFixedT(locale);
        c.set(i18nSymbol, i18n);
        c.set(LocaleSymbol, locale);
        c.set(TSymbol, t);
        await next();
    });
}

this returns the string 'en'

however

i18next.getLocale = function getLocale(c) {
    let locale = c.get(LocaleSymbol);
    console.log("getLocale", locale);
		if (!locale) {
        throw new Error("The i18next middleware must run before calling `i18next.getLocale()`");
    }
    return locale;
};

is returning the string '[Function: fixedT] { lng: 'en', ns: undefined, keyPrefix: undefined }'

**Comment by JasonColeyNZ** [comment]
Ok this fixes the issue... at the top the Symbol declarations..

const i18nSymbol = Symbol('i18nSymbol').toString();
const LocaleSymbol = Symbol('LocaleSymbol').toString();
const TSymbol = Symbol('TSymbol').toString();

Changing to this fixes the issue, I don't fully understand how Symbols work, but the Symbol().String() just returns 'Symbol()' in the string, so the c.set() were basically overwriting themselves, so c.get(LocaleSymbol) was actually getting what was set in c.set(TSymbol, t), the last of the set statements in the createMiddleware function

**Comment by JasonColeyNZ** [comment]
It happened in Commit bc12d09 by @rphlmr by the looks of it?
I think i did something when I first started playing with Symbols, ts was complaining about them, can't remember now exactly what the issue was

**Comment by rphlmr** [comment]
@JasonColeyNZ oh 👀 it’s possible I forgot to rollback this change.
Will look at it during the day.

**Comment by rphlmr** [comment]
@JasonColeyNZ I've made a PR. I'm not sure how you can test it, but maybe you can edit the JS file in your `node_modules` to remove the `.toString()` (this is what this PR does).
